# Generated by Django 4.1.1 on 2022-12-29 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='myuser',
            managers=[
            ],
        ),
    ]
