# Generated by Django 4.1.1 on 2022-12-30 12:08

import account.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_myuser_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='myuser',
            managers=[
                ('objects', account.manager.UserManager()),
            ],
        ),
    ]
