# Generated by Django 4.1.1 on 2023-02-03 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_myuser_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='joining_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
