# Generated by Django 4.1.1 on 2023-02-05 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_myuser_joining_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='confirm_password',
            field=models.CharField(max_length=150, null=True, verbose_name='Confirm Password'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='password',
            field=models.CharField(max_length=150, verbose_name='Password'),
        ),
    ]
