# Generated by Django 4.1.7 on 2023-04-28 14:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0005_myuser_confirm_password_alter_myuser_password"),
    ]

    operations = [
        migrations.CreateModel(
            name="otp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("otp", models.CharField(max_length=6)),
                ("email", models.EmailField(max_length=254)),
            ],
        ),
        migrations.AddField(
            model_name="myuser",
            name="reward_point",
            field=models.IntegerField(default=0),
        ),
    ]
