# Generated by Django 4.1.7 on 2023-05-02 08:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import embed_video.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='movieCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_name', models.CharField(max_length=50)),
                ('certificate_des', models.TextField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='movieLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_name', models.CharField(max_length=50)),
                ('language_des', models.TextField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_slider', models.ImageField(blank=True, null=True, upload_to='movies_images/')),
                ('movie_img', models.ImageField(upload_to='movies_images/')),
                ('movie_title', models.CharField(max_length=50)),
                ('movie_cast', models.TextField(max_length=250)),
                ('movie_director', models.CharField(blank=True, max_length=200, null=True)),
                ('release_date', models.DateTimeField(blank=True, max_length=50, null=True)),
                ('movie_duration', models.CharField(blank=True, max_length=50, null=True)),
                ('movie_trailer', embed_video.fields.EmbedVideoField()),
                ('movie_price', models.CharField(blank=True, max_length=50, null=True)),
                ('movie_des', models.TextField(blank=True, max_length=250, null=True)),
                ('movie_certificate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Movies.moviecertificate')),
                ('movie_language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Movies.movielanguage')),
            ],
        ),
        migrations.CreateModel(
            name='movieShowtime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('showtime', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='movieType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=50)),
                ('type_des', models.TextField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Seats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booked_seats', models.JSONField(blank=True, verbose_name=models.CharField(max_length=3))),
                ('movie_title', models.CharField(max_length=30)),
                ('movie_date', models.CharField(blank=True, max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('ticket_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('movie_date', models.CharField(blank=True, max_length=11)),
                ('movie_title', models.CharField(max_length=50, null=True)),
                ('seat_number', models.CharField(blank=True, max_length=50)),
                ('movie_showtime', models.CharField(blank=True, max_length=12)),
                ('price', models.CharField(max_length=5)),
                ('bought_at', models.DateTimeField(auto_now=True)),
                ('movie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Movies.movies')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='movies',
            name='movie_showtime',
            field=models.ManyToManyField(blank=True, to='Movies.movieshowtime'),
        ),
        migrations.AddField(
            model_name='movies',
            name='movie_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Movies.movietype'),
        ),
    ]
