# Generated by Django 4.1.1 on 2022-12-29 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_slider', models.FileField(default=None, max_length=250, null=True, upload_to='movies_images/')),
                ('movie_img', models.FileField(default=None, max_length=250, upload_to='movies_images/')),
                ('movie_title', models.CharField(max_length=200)),
                ('movie_cast', models.TextField()),
            ],
        ),
    ]
