# Generated by Django 4.1.1 on 2023-01-07 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Movies',
            new_name='Moviess',
        ),
    ]
