# Generated by Django 4.1.7 on 2023-05-19 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0002_moviestatus_movies_movie_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movieshowtime',
            old_name='showtime_name',
            new_name='showtime',
        ),
        migrations.AddField(
            model_name='movies',
            name='uploaded_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
