# Generated by Django 4.1.1 on 2023-01-07 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0002_rename_movies_moviess'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Moviess',
            new_name='Movies',
        ),
    ]
