# Generated by Django 4.1.1 on 2023-01-13 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0003_rename_moviess_movies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='img_slider',
            field=models.ImageField(default=None, max_length=250, null=True, upload_to='movies_images/'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='movie_img',
            field=models.ImageField(default=None, max_length=250, upload_to='movies_images/'),
        ),
    ]
