# Generated by Django 4.1.7 on 2023-05-19 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0003_rename_showtime_name_movieshowtime_showtime_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies',
            name='uploaded_at',
        ),
    ]
