# Generated by Django 4.1.1 on 2023-01-13 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0004_alter_movies_img_slider_alter_movies_movie_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='img_slider',
            field=models.ImageField(default='', upload_to='movies_images/'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='movie_cast',
            field=models.TextField(max_length=250),
        ),
        migrations.AlterField(
            model_name='movies',
            name='movie_img',
            field=models.ImageField(default='', upload_to='movies_images/'),
        ),
    ]
