# Generated by Django 4.1.7 on 2023-05-22 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0004_remove_movies_uploaded_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='uploaded_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
