# Generated by Django 4.1.1 on 2023-02-08 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0006_alter_movies_img_slider_alter_movies_movie_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='movieCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_name', models.CharField(max_length=50)),
                ('certificate_des', models.TextField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='movieLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_name', models.CharField(max_length=50)),
                ('language_des', models.TextField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='movieShowtime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('showtime_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='movieType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=50)),
                ('type_des', models.TextField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='movies',
            name='movie_des',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='movie_director',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='movie_duration',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='movie_price',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='movie_trailer',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='release_date',
            field=models.DateTimeField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='movies',
            name='img_slider',
            field=models.ImageField(blank=True, null=True, upload_to='movies_images/'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='movie_title',
            field=models.CharField(max_length=50),
        ),
        migrations.AddField(
            model_name='movies',
            name='movie_certificate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Movies.moviecertificate'),
        ),
        migrations.AddField(
            model_name='movies',
            name='movie_language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Movies.movielanguage'),
        ),
        migrations.AddField(
            model_name='movies',
            name='movie_showtime',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Movies.movieshowtime'),
        ),
        migrations.AddField(
            model_name='movies',
            name='movie_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Movies.movietype'),
        ),
    ]
