# Generated by Django 4.1.1 on 2023-02-23 08:31

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0007_moviecertificate_movielanguage_movieshowtime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='movie_trailer',
            field=embed_video.fields.EmbedVideoField(),
        ),
    ]
