# Generated by Django 4.1.7 on 2023-03-28 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0008_alter_movies_movie_trailer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booked_seats', models.JSONField(blank=True, verbose_name=models.CharField(max_length=3))),
                ('movie_title', models.CharField(max_length=30)),
                ('movie_date', models.CharField(blank=True, max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('ticket_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('movie_date', models.CharField(blank=True, max_length=11)),
                ('movie_title', models.CharField(max_length=30)),
                ('seat_number', models.CharField(blank=True, max_length=50)),
                ('movie_showtime', models.CharField(blank=True, max_length=12)),
                ('price', models.CharField(max_length=5)),
                ('bought_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
