# Generated by Django 4.1.7 on 2023-05-13 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0010_ticket_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movieshowtime',
            old_name='showtime_name',
            new_name='showtime',
        ),
        migrations.AddField(
            model_name='ticket',
            name='movie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Movies.movies'),
        ),
        migrations.RemoveField(
            model_name='movies',
            name='movie_showtime',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='movie_title',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='movie_showtime',
            field=models.ManyToManyField(blank=True, to='Movies.movieshowtime'),
        ),
    ]
